name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Black (check)
        run: black --check .
      - name: Pylint
        run: pylint src
      - name: Pytest
        env:
          DATABASE_URL: "sqlite+pysqlite:///:memory:"
          PYTHONPATH: "${{ github.workspace }}/src"
        run: pytest -q
